# Generated by Django 5.1.3 on 2026-01-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naziv musterije', max_length=250)),
                ('vat_id', models.IntegerField(help_text='Vat id broj', unique=True)),
                ('street', models.CharField(help_text='Naziv ulice', max_length=250)),
                ('city', models.CharField(help_text='Ime grada', max_length=250)),
                ('country', models.CharField(help_text='Ime drzave', max_length=250)),
            ],
        ),
    ]
